### ISSUE TITLE
Port to N20 motors?

### ISSUE THREAD

**Issue by samuk** [UEA-envsoft/Otto-Mecanum#1]
Hi nice project.

I'm working on a open hardware mecanum https://rosmo-robot.github.io/ planning to sell as a kit soon.

Bit of a longshot, but I don't suppose you fancy porting your Python & App code over to that?

I already have Microblocks & ROS2 underway, but it would be nice to give people a Python version too.

I could probably post you a PCB if you wanted to give it a go

**Comment by UEA-envsoft** [comment]
I'll be in touch :)

**Comment by samuk** [comment]
Nice, dropped you a mail. Closing to keep your issues tidy.
